DROP TABLE IF EXISTS USER_AUTHORITY;

DROP TABLE IF EXISTS BOOK_GENRE;

DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS AUTHORITY;

DROP TABLE IF EXISTS COMMENT;

DROP TABLE IF EXISTS AUTHOR;

DROP TABLE IF EXISTS GENRE;

DROP TABLE IF EXISTS BOOK;

CREATE TABLE USERS(ID BIGINT IDENTITY PRIMARY KEY, LOGIN VARCHAR(255), PASSWORD_HASH VARCHAR(60), IS_ACTIVE BOOLEAN NOT NULL);

CREATE TABLE AUTHORITY(NAME VARCHAR(50) NOT NULL);

CREATE TABLE AUTHOR(ID BIGINT IDENTITY PRIMARY KEY, FULL_NAME VARCHAR(255));

CREATE TABLE GENRE(ID BIGINT IDENTITY PRIMARY KEY, GENRE_NAME VARCHAR(255));

CREATE TABLE BOOK(ID BIGINT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT);

CREATE TABLE COMMENT(ID BIGINT IDENTITY PRIMARY KEY, USER_NAME VARCHAR(255), TEXT VARCHAR(255), BOOK_ID BIGINT,
                     CONSTRAINT `fk_comment_book_id` FOREIGN KEY(`BOOK_ID`) REFERENCES `BOOK` (`ID`) ON DELETE CASCADE);

CREATE TABLE BOOK_GENRE(BOOK_ID BIGINT NOT NULL, GENRE_ID BIGINT NOT NULL,
                        PRIMARY KEY (`BOOK_ID`, `GENRE_ID`),
                        CONSTRAINT `fk_book_genre_book_id` FOREIGN KEY(`BOOK_ID`) REFERENCES `BOOK` (`ID`),
                        CONSTRAINT `fk_book_genre_genre_id` FOREIGN KEY(`GENRE_ID`) REFERENCES `GENRE` (`ID`));

CREATE TABLE USER_AUTHORITY(USER_ID BIGINT NOT NULL, AUTHORITY_NAME VARCHAR(50) NOT NULL,
                        PRIMARY KEY (`USER_ID`, `AUTHORITY_NAME`),
                        CONSTRAINT `fk_user_authority_user_id` FOREIGN KEY(`USER_ID`) REFERENCES `USERS` (`ID`),
                        CONSTRAINT `fk_user_authority_authority_name` FOREIGN KEY(`AUTHORITY_NAME`) REFERENCES `AUTHORITY` (`NAME`));