apiVersion: v1
kind: ConfigMap
metadata:
  name: vinyl-library-config
  namespace: default
data:
  application.yml: |
    spring:
      application:
        name: vinyl-library
      datasource:
        url: jdbc:postgresql://postgres-service:5432/vinyldb
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            format_sql: true
        show-sql: false
      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
        enabled: true
      batch:
        jdbc:
          initialize-schema: always
        job:
          enabled: false
      shell:
        interactive:
          enabled: false
    jwt:
      secret: alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984
      sessionTime: 1200000000
    management:
      endpoints:
        web:
          exposure:
            include: health, info, metrics, prometheus
      endpoint:
        health:
          show-details: always
    logging:
      level:
        root: INFO
        ru.otus.vivlev: DEBUG
    server:
      port: 8080
