apiVersion: v1
kind: Secret
metadata:
  name: vinyl-library-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984alexander1984"
  db-password: "postgres"
