insert into author (full_name) values ('Гаррисон, Г.');
insert into author (full_name) values ('Перумов, Н.');
insert into genre (genre_name) values ('Фантастика');
insert into genre (genre_name) values ('Фентези');
insert into book (title, author_id) values ('Стальная крыса идет на войну', 1);
insert into book (title, author_id) values ('Стальная крыса спасает мир', 1);
insert into book (title, author_id) values ('Не время для драконов', 2);
insert into book_genre  (book_id, genre_id) values (1, 1);
insert into book_genre  (book_id, genre_id) values (2, 1);
insert into book_genre  (book_id, genre_id) values (3, 2);