DROP TABLE IF EXISTS BOOK_GENRE;

DROP TABLE IF EXISTS COMMENT;

DROP TABLE IF EXISTS AUTHOR;

DROP TABLE IF EXISTS GENRE;

DROP TABLE IF EXISTS BOOK;

CREATE TABLE AUTHOR(ID BIGINT IDENTITY PRIMARY KEY, FULL_NAME VARCHAR(255));

CREATE TABLE GENRE(ID BIGINT IDENTITY PRIMARY KEY, GENRE_NAME VARCHAR(255));

CREATE TABLE BOOK(ID BIGINT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT);

CREATE TABLE COMMENT(ID BIGINT IDENTITY PRIMARY KEY, USER_NAME VARCHAR(255), TEXT VARCHAR(255), BOOK_ID BIGINT,
                     CONSTRAINT `fk_comment_book_id` FOREIGN KEY(`BOOK_ID`) REFERENCES `BOOK` (`ID`) ON DELETE CASCADE);

CREATE TABLE BOOK_GENRE(BOOK_ID BIGINT NOT NULL, GENRE_ID BIGINT NOT NULL,
                        PRIMARY KEY (`BOOK_ID`, `GENRE_ID`),
                        CONSTRAINT `fk_book_genre_book_id` FOREIGN KEY(`BOOK_ID`) REFERENCES `BOOK` (`ID`),
                        CONSTRAINT `fk_book_genre_genre_id` FOREIGN KEY(`GENRE_ID`) REFERENCES `GENRE` (`ID`));
